# Generated by Django 5.1.7 on 2025-03-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
