# Generated by Django 5.1.7 on 2025-03-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_trainee_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='img',
            field=models.ImageField(default=33, upload_to='trainee/image'),
            preserve_default=False,
        ),
    ]
